# Generated by Django 3.0.3 on 2020-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateField(blank=True, null=True)),
                ('up_to_date', models.DateField(blank=True, null=True)),
                ('tax_rate', models.FloatField(default=0.0)),
                ('is_rough', models.BooleanField(default=True)),
                ('equasion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateField(blank=True, null=True)),
                ('up_to_date', models.DateField(blank=True, null=True)),
                ('tariff', models.FloatField(default=0.0)),
            ],
        ),
    ]
