# Generated by Django 3.0.3 on 2020-02-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbird', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateField(blank=True, null=True)),
                ('up_to_date', models.DateField(blank=True, null=True)),
                ('tariff', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='formula',
            name='tariff',
        ),
    ]
