# Generated by Django 3.0.5 on 2020-04-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbird', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'verbose_name_plural': 'Формулы'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name_plural': 'Тарифы'},
        ),
    ]
