"""2 migration

Revision ID: 0737cf5121da
Revises: d69c239f2f67
Create Date: 2019-12-18 09:24:32.960284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0737cf5121da'
down_revision = 'd69c239f2f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contragent', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contragent', 'test')
    # ### end Alembic commands ###
