"""empty message

Revision ID: 484b3d8c83cd
Revises: 
Create Date: 2019-12-16 07:21:10.774775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484b3d8c83cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
