"""Add klassType model

Revision ID: 872b996d069a
Revises: f165b9318d5b
Create Date: 2019-12-18 07:23:57.677213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872b996d069a'
down_revision = 'f165b9318d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contragent', 'klass',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contragent', 'klass',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
