"""rename date field to reg_date

Revision ID: b96159fd818f
Revises: ceb199fd6f15
Create Date: 2019-12-19 02:24:06.465829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96159fd818f'
down_revision = 'ceb199fd6f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contragent', sa.Column('reg_date', sa.Date(), nullable=True))
    op.drop_column('contragent', 'date')
    op.drop_column('contragent', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contragent', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contragent', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('contragent', 'reg_date')
    # ### end Alembic commands ###
