"""1 migration

Revision ID: d69c239f2f67
Revises: ee190356f18c
Create Date: 2019-12-18 09:17:30.664192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69c239f2f67'
down_revision = 'ee190356f18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
