"""empty message

Revision ID: ead2be419aa0
Revises: 484b3d8c83cd
Create Date: 2019-12-16 07:22:59.319090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead2be419aa0'
down_revision = '484b3d8c83cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contragent',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('ur_adress', sa.String(), nullable=True),
    sa.Column('fuct_adress', sa.String(), nullable=True),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('klass', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contragent_id'), 'contragent', ['id'], unique=False)
    op.create_index(op.f('ix_contragent_name'), 'contragent', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contragent_name'), table_name='contragent')
    op.drop_index(op.f('ix_contragent_id'), table_name='contragent')
    op.drop_table('contragent')
    # ### end Alembic commands ###
