"""init migration

Revision ID: ee190356f18c
Revises: 
Create Date: 2019-12-18 09:01:05.038563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee190356f18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contragent',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('fuct_adress', sa.String(), nullable=True),
    sa.Column('klass', postgresql.ENUM('ur', 'fl', name='klass_enum'), nullable=False),
    sa.Column('ur_adress', sa.String(), nullable=True),
    sa.Column('ogrn', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contragent_id'), 'contragent', ['id'], unique=False)
    op.create_index(op.f('ix_contragent_name'), 'contragent', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contragent_name'), table_name='contragent')
    op.drop_index(op.f('ix_contragent_id'), table_name='contragent')
    op.drop_table('contragent')
    # ### end Alembic commands ###
