"""Swap ur_adress and fukt_adress

Revision ID: f165b9318d5b
Revises: ead2be419aa0
Create Date: 2019-12-18 04:05:25.275860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f165b9318d5b'
down_revision = 'ead2be419aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
