# Generated by Django 3.0.7 on 2020-07-08 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yellowbird', '0005_auto_20200428_0321'),
        ('redbird', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона отчета')),
                ('file_path', models.FileField(upload_to='', verbose_name='Template file')),
                ('data_set', models.ManyToManyField(to='redbird.DataPart')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('departments', models.ManyToManyField(blank=True, null=True, to='yellowbird.Department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbird.ReportTemplate')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
