# Generated by Django 3.0.7 on 2020-07-24 07:17

from django.db import migrations, models
import redbird.agregators


class Migration(migrations.Migration):

    dependencies = [
        ('redbird', '0002_datapart_report_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapart',
            name='agregator',
            field=models.IntegerField(choices=[(0, None), (1, redbird.agregators.JournalAgregator)], default=0, unique=True),
        ),
    ]
