# Generated by Django 3.0.7 on 2020-07-27 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowbird', '0005_auto_20200428_0321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redbird', '0003_datapart_agregator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='departments',
            field=models.ManyToManyField(blank=True, to='yellowbird.Department'),
        ),
        migrations.AlterField(
            model_name='report',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
