# Generated by Django 3.0.5 on 2020-04-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowbird', '0002_auto_20200421_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Отделы'},
        ),
    ]
