# Generated by Django 3.0.5 on 2020-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowbird', '0003_auto_20200422_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='strategy',
            field=models.CharField(choices=[(0, 'Мои записи и пустые'), (1, 'Все по отделу'), (2, 'Все'), (3, 'Только мои записи'), (4, 'Только пустые записи')], default=0, max_length=255, verbose_name='Стратегия отсеивания результатов'),
        ),
    ]
