# Generated by Django 3.0.5 on 2020-04-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowbird', '0004_auto_20200424_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='strategy',
            field=models.IntegerField(choices=[(0, 'Мои записи и пустые'), (1, 'Все по отделу'), (2, 'Все'), (3, 'Только мои записи'), (4, 'Только пустые записи')], default=0, verbose_name='Стратегия отсеивания результатов'),
        ),
    ]
