# Generated by Django 3.0.3 on 2020-03-13 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluebird', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contragent',
            name='norm_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normatives', to='bluebird.NormativeCategory'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='number_contract',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.ContractNumberClass'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='signed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed', to='bluebird.SignUser'),
        ),
        migrations.AddField(
            model_name='contractnumberclass',
            name='contract_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.Contract'),
        ),
    ]
