# Generated by Django 3.0.5 on 2020-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0002_auto_20200313_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'Сгенерированые номера договоров'},
        ),
        migrations.AlterModelOptions(
            name='contractnumberclass',
            options={'verbose_name_plural': 'Номера договоров'},
        ),
        migrations.AlterModelOptions(
            name='contragent',
            options={'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='documentspackage',
            options={'verbose_name_plural': 'Пакеты документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttypemodel',
            options={'verbose_name_plural': 'Типы документов'},
        ),
        migrations.AlterModelOptions(
            name='normative',
            options={'verbose_name_plural': 'Нормативы'},
        ),
        migrations.AlterModelOptions(
            name='normativecategory',
            options={'verbose_name_plural': 'Категории нормативов'},
        ),
        migrations.AlterModelOptions(
            name='otherfile',
            options={'verbose_name_plural': 'Прочие файлы'},
        ),
        migrations.AlterModelOptions(
            name='packfile',
            options={'verbose_name_plural': 'Фаилы набора'},
        ),
        migrations.AlterModelOptions(
            name='packfilestemplate',
            options={'verbose_name_plural': 'Шаблоны наборов файлов'},
        ),
        migrations.AlterModelOptions(
            name='signuser',
            options={'verbose_name_plural': 'Отвественные лица с правом подписи'},
        ),
        migrations.AlterModelOptions(
            name='singlefile',
            options={'verbose_name_plural': 'Единичные файлы'},
        ),
        migrations.AlterModelOptions(
            name='singlefilestemplate',
            options={'verbose_name_plural': 'Шаблоны единичных файлов'},
        ),
        migrations.AlterModelOptions(
            name='syncuniquenumber',
            options={'verbose_name_plural': 'Номера документов'},
        ),
        migrations.AlterModelOptions(
            name='templatemodel',
            options={'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AddField(
            model_name='signuser',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='signs/', verbose_name='Подпись'),
        ),
    ]
