# Generated by Django 3.0.5 on 2020-04-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0004_auto_20200421_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='events_set',
        ),
        migrations.AddField(
            model_name='event',
            name='from_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begin_states', to='bluebird.State', verbose_name='Исходное состояние'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_final_state',
            field=models.BooleanField(default=False, verbose_name='Конечное состояние'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_initial_state',
            field=models.BooleanField(default=False, verbose_name='Начальное состояние'),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_states', to='bluebird.State', verbose_name='Конечное состояние'),
        ),
    ]
