# Generated by Django 3.0.5 on 2020-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0005_auto_20200422_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'Состояния'},
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='package_state_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего действия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_event',
            field=models.CharField(max_length=255, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name_state',
            field=models.CharField(max_length=255, verbose_name='Состояние'),
        ),
    ]
