# Generated by Django 3.0.5 on 2020-04-28 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('yellowbird', '0005_auto_20200428_0321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluebird', '0006_auto_20200424_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='departments',
            field=models.ManyToManyField(related_name='available_states', to='yellowbird.Department', verbose_name='Отделы'),
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary_text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
