# Generated by Django 3.0.5 on 2020-05-06 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluebird', '0007_auto_20200428_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contragent',
            name='current_user',
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='package_users',
            field=models.ManyToManyField(related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
