# Generated by Django 3.0.2 on 2020-01-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0007_auto_20200110_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contragent',
            old_name='nunber_contract',
            new_name='number_contract',
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='norm_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normatives', to='bluebird.NormativeCategory'),
        ),
    ]
