# Generated by Django 3.0.2 on 2020-01-20 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0008_auto_20200113_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUniqueNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='contragent',
            name='contract_accept_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 7, 1), null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания контрагента (юл)'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Текущая дата'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='dadata_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование контрагента (из Dadata)'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='debt',
            field=models.FloatField(default=0.0, verbose_name='Сумма задолжности'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя либо иное наименование директора'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='director_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор (физ. лицо либо юр. лицо)'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='excell_name',
            field=models.CharField(max_length=255, verbose_name='Наименование контрагента (из Excell)'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ИНН контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='is_func',
            field=models.BooleanField(default=True, verbose_name='Признак активности контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='klass',
            field=models.CharField(choices=[(1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=1, max_length=255, verbose_name='Класс контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='kpp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='КПП контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адресс'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='ogrn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ОГРН контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='okved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='physical_address',
            field=models.CharField(max_length=255, verbose_name='Физический адресс'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='platform',
            field=models.IntegerField(blank=True, null=True, verbose_name='№ площадки'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='stat_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='since_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия норматива'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='up_to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия норматива'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение норматива (мес.)'),
        ),
        migrations.AlterField(
            model_name='normativecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Вид объекта'),
        ),
        migrations.CreateModel(
            name='DocumentUniqueNumberGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_when', models.DateField(blank=True, null=True)),
                ('contragent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.Contragent')),
                ('unique_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentUniqueNumber')),
            ],
        ),
        migrations.CreateModel(
            name='ContractNumberClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_generated', models.BooleanField(default=False)),
                ('contract_exist_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contract_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.Contract')),
            ],
        ),
        migrations.AlterField(
            model_name='contragent',
            name='number_contract',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.ContractNumberClass'),
        ),
    ]
