# Generated by Django 3.0.7 on 2020-07-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0008_auto_20200506_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFileTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagent_type', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=0)),
                ('is_package', models.BooleanField(default=False, verbose_name='Набор файлов')),
            ],
            options={
                'verbose_name_plural': 'Шаблоны файлов',
            },
        ),
        migrations.CreateModel(
            name='DocumentStateEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.ManyToManyField(related_name='document_type', to='bluebird.DocumentTypeModel')),
                ('states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='bluebird.State')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentFileTemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='singlefilestemplate',
            name='documents',
        ),
        migrations.AddField(
            model_name='contragent',
            name='debt_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество неоплаченных периодов, мес.'),
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='debt_fact',
            field=models.FloatField(default=0.0, verbose_name='Сумма задолжности (фактическая)'),
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='debt_plan',
            field=models.FloatField(default=0.0, verbose_name='Сумма задолжности (плановая)'),
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='is_automatic',
            field=models.BooleanField(default=True, verbose_name='Создан автоматически'),
        ),
        migrations.AddField(
            model_name='documentspackage',
            name='tax_count',
            field=models.FloatField(default=0.0, verbose_name='Госпошлина'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_move_backward',
            field=models.BooleanField(default=False, verbose_name='Двигаемся обратно назад'),
        ),
        migrations.DeleteModel(
            name='PackFilesTemplate',
        ),
        migrations.DeleteModel(
            name='SingleFilesTemplate',
        ),
    ]
