# Generated by Django 3.0.7 on 2020-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0009_auto_20200703_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
        ),
        migrations.AddField(
            model_name='contragent',
            name='fss_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contragent',
            name='judge_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contragent',
            name='passport_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='personal_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лицевой счет'),
        ),
    ]
