# Generated by Django 3.0.2 on 2020-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0009_auto_20200120_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='klass',
            field=models.IntegerField(choices=[(0, 'Пусто'), (1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=0, verbose_name='Класс контрагента'),
        ),
        migrations.AlterField(
            model_name='normativecategory',
            name='normative',
            field=models.ManyToManyField(related_name='normatives', to='bluebird.Normative', verbose_name='Нормативы'),
        ),
    ]
