# Generated by Django 3.0.7 on 2020-07-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0010_auto_20200708_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи пасспорта'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='passport_origin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Кем выдан пасспорт'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='snils',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='СНИЛС'),
        ),
    ]
