# Generated by Django 3.0.2 on 2020-01-24 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0011_auto_20200122_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountFactUN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contragent',
            name='contract_accept_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 7, 1), null=True, verbose_name='Дата начала оказания услуг'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Конечная дата оказания услуг'),
        ),
        migrations.CreateModel(
            name='CountFactUNGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_when', models.DateField(blank=True, null=True)),
                ('contragent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.Contragent')),
                ('unique_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bluebird.CountFactUN')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
