# Generated by Django 3.0.2 on 2020-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0012_auto_20200124_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativecategory',
            name='norm_type',
            field=models.IntegerField(blank=True, choices=[(0, '1 м2 общей площади'), (1, '1 место'), (2, '1 человек')], default=0, null=True, verbose_name='Показатель расчета'),
        ),
    ]
