# Generated by Django 3.0.2 on 2020-01-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bluebird', '0013_normativecategory_norm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('object_id', models.PositiveIntegerField()),
                ('file_obj', models.FileField(upload_to='', verbose_name='Произвольные файлы')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пакет')),
                ('contract', models.FileField(blank=True, null=True, upload_to='', verbose_name='Договор')),
                ('court_note', models.FileField(blank=True, null=True, upload_to='', verbose_name='Претензия')),
                ('act_count', models.FileField(upload_to='', verbose_name='Акт сверки')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contragents', related_query_name='contragent', to='bluebird.Contragent')),
            ],
        ),
        migrations.CreateModel(
            name='CountFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('object_id', models.PositiveIntegerField()),
                ('file_obj', models.FileField(upload_to='', verbose_name='Счет на оплату')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountFactFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('object_id', models.PositiveIntegerField()),
                ('file_obj', models.FileField(upload_to='', verbose_name='Счет фактура')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('object_id', models.PositiveIntegerField()),
                ('file_obj', models.FileField(upload_to='', verbose_name='Акт')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
