# Generated by Django 3.0.2 on 2020-01-28 08:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0014_actfile_countfactfile_countfile_documentspackage_otherfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspackage',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания пакета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentspackage',
            name='name_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
