# Generated by Django 3.0.2 on 2020-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0017_auto_20200128_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actfile',
            name='file_obj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Акт'),
        ),
    ]
