# Generated by Django 3.0.2 on 2020-01-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0019_actfile_number_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActUniqueNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountFactUniqueNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountUniqueNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='actungen',
            name='contragent',
        ),
        migrations.RemoveField(
            model_name='actungen',
            name='unique_number',
        ),
        migrations.RemoveField(
            model_name='countfactungen',
            name='contragent',
        ),
        migrations.RemoveField(
            model_name='countfactungen',
            name='unique_number',
        ),
        migrations.RemoveField(
            model_name='countungen',
            name='contragent',
        ),
        migrations.RemoveField(
            model_name='countungen',
            name='unique_number',
        ),
        migrations.RemoveField(
            model_name='actfile',
            name='file_obj',
        ),
        migrations.RemoveField(
            model_name='actfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='actfile',
            name='number_obj',
        ),
        migrations.RemoveField(
            model_name='countfactfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='countfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='otherfile',
            name='name',
        ),
        migrations.AddField(
            model_name='actfile',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания файла'),
        ),
        migrations.AddField(
            model_name='actfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='actfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='countfactfile',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания файла'),
        ),
        migrations.AddField(
            model_name='countfactfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='countfactfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='countfile',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания файла'),
        ),
        migrations.AddField(
            model_name='countfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='countfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='otherfile',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания файла'),
        ),
        migrations.AddField(
            model_name='otherfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='otherfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь'),
        ),
        migrations.DeleteModel(
            name='ActUN',
        ),
        migrations.DeleteModel(
            name='ActUNGen',
        ),
        migrations.DeleteModel(
            name='CountFactUN',
        ),
        migrations.DeleteModel(
            name='CountFactUNGen',
        ),
        migrations.DeleteModel(
            name='CountUN',
        ),
        migrations.DeleteModel(
            name='CountUNGen',
        ),
        migrations.AddField(
            model_name='actfile',
            name='act_unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.ActUniqueNumber'),
        ),
    ]
