# Generated by Django 3.0.2 on 2020-01-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0020_auto_20200129_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countfactfile',
            name='file_obj',
        ),
        migrations.RemoveField(
            model_name='countfile',
            name='file_obj',
        ),
        migrations.AddField(
            model_name='countfactfile',
            name='act_unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.CountFactUniqueNumber'),
        ),
        migrations.AddField(
            model_name='countfile',
            name='count_unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.CountUniqueNumber'),
        ),
    ]
