# Generated by Django 3.0.2 on 2020-01-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0021_auto_20200130_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countfactfile',
            old_name='act_unique_number',
            new_name='count_fact_unique_number',
        ),
    ]
