# Generated by Django 3.0.2 on 2020-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0023_auto_20200131_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentspackage',
            name='act_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Акт сверки'),
        ),
        migrations.AlterField(
            model_name='documentspackage',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='documentspackage',
            name='court_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Претензия'),
        ),
    ]
