# Generated by Django 3.0.3 on 2020-02-17 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0024_auto_20200131_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО отвественного лица')),
                ('document', models.IntegerField(choices=[(0, 'Доверенность'), (1, 'Пасспорт')], default=0, verbose_name='Документ основания')),
                ('position', models.IntegerField(choices=[(0, 'Клиент-менеджер'), (1, 'Старший менеджер по работе с ЮЛ'), (2, 'Менеджер')], default=0, verbose_name='Должность')),
                ('doc_number', models.CharField(max_length=255, verbose_name='Номер документа')),
                ('doc_date', models.DateField(verbose_name='Дата начала действия документа')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('tel_number', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterField(
            model_name='documentspackage',
            name='name_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, null=True, verbose_name='Идентификатор пакета'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='signed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed', to='bluebird.SignUser'),
        ),
    ]
