# Generated by Django 3.0.3 on 2020-02-27 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0025_auto_20200217_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип документа')),
            ],
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Конечная дата оказания услуг'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение норматива (год.)'),
        ),
        migrations.AlterField(
            model_name='signuser',
            name='tel_number',
            field=models.CharField(default='', max_length=255, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_path', models.CharField(max_length=255, verbose_name='Путь до шаблона')),
                ('contragent_type', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=0, verbose_name='Тип контрагента')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluebird.CityModel')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentTypeModel', verbose_name='Тип документа')),
            ],
        ),
        migrations.AddField(
            model_name='signuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.CityModel'),
        ),
    ]
