# Generated by Django 3.0.3 on 2020-03-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bluebird', '0026_auto_20200227_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFilesTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagent_type', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=0)),
                ('documents', models.ManyToManyField(related_name='document_types', to='bluebird.DocumentTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='SingleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата создания файла')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentTypeModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
