# Generated by Django 3.0.3 on 2020-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0026_auto_20200225_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuser',
            name='city',
            field=models.CharField(default='Кемерово', max_length=255, verbose_name='Город/населенный пункт'),
        ),
    ]
