# Generated by Django 3.0.3 on 2020-03-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0027_singlefile_singlefilestemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentspackage',
            name='act_count',
        ),
        migrations.RemoveField(
            model_name='documentspackage',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='documentspackage',
            name='court_note',
        ),
    ]
