# Generated by Django 3.0.3 on 2020-03-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bluebird', '0028_auto_20200302_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата создания файла')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackFilesTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagent_type', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncUniqueNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='countfactfile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='countfactfile',
            name='count_fact_unique_number',
        ),
        migrations.RemoveField(
            model_name='countfile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='countfile',
            name='count_unique_number',
        ),
        migrations.AddField(
            model_name='documenttypemodel',
            name='is_pack',
            field=models.BooleanField(default=False, verbose_name='Пакет документов'),
        ),
        migrations.AddField(
            model_name='otherfile',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentTypeModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singlefilestemplate',
            name='documents',
            field=models.ManyToManyField(related_name='document_type', to='bluebird.DocumentTypeModel'),
        ),
        migrations.DeleteModel(
            name='ActFile',
        ),
        migrations.DeleteModel(
            name='ActUniqueNumber',
        ),
        migrations.DeleteModel(
            name='CountFactFile',
        ),
        migrations.DeleteModel(
            name='CountFactUniqueNumber',
        ),
        migrations.DeleteModel(
            name='CountFile',
        ),
        migrations.DeleteModel(
            name='CountUniqueNumber',
        ),
        migrations.AddField(
            model_name='packfilestemplate',
            name='documents',
            field=models.ManyToManyField(related_name='document_type_pack', to='bluebird.DocumentTypeModel'),
        ),
        migrations.AddField(
            model_name='packfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluebird.DocumentTypeModel'),
        ),
        migrations.AddField(
            model_name='packfile',
            name='unique_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluebird.SyncUniqueNumber'),
        ),
    ]
