# Generated by Django 3.0.3 on 2020-03-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0029_auto_20200311_0902'),
        ('bluebird', '0026_auto_20200226_0932'),
    ]

    operations = [
    ]
