# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sendmail:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send mailer
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.yandex.ru
          port: 587 # optional, default is 465
          account: ${{secrets.EMAIL_ACCOUNT}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          sender: CI accountant_app
          from: ${{ secrets.EMAIL_ACCOUNT }}
          to: ${{ secrets.EMAIL_DOXOPOKC }}
          subject: new change
          body: file://README.md
