name: clrn stage CI

on:
  push:
    branches:
      - dev
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create .env
      run: cp /var/local/jud-module/.env ./.env
    - name: Create volumes
      run: |
        docker volume create db_data
    - name: Make upb
      run: make upb
